import streamlit as st
import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# --- PAGE CONFIG ---
st.set_page_config(page_title="Chi-Town Sentinel", layout="wide")

# --- LOAD MODELS & ASSETS ---
@st.cache_resource
def load_assets():
    models = {
        "Random Forest": joblib.load('random_forest_model.pkl'),
        "Decision Tree": joblib.load('decision_tree_model.pkl'),
        "Logistic Regression": joblib.load('logistic_regression_model.pkl')
    }
    # Load XGBoost if available
    try:
        models["XGBoost"] = joblib.load('xgboost_model.pkl')
    except:
        pass
        
    scaler = joblib.load('scaler.pkl')
    thresholds = joblib.load('optimal_thresholds.pkl')
    return models, scaler, thresholds

models, scaler, thresholds = load_assets()

# --- SIDEBAR: MODEL SELECTION ---
st.sidebar.title("🛡️ Chi-Town Sentinel")
st.sidebar.markdown("### Model Controls")
selected_model_name = st.sidebar.selectbox("Select Model Architecture", list(models.keys()))
current_model = models[selected_model_name]

# Allow real-time threshold adjustment
default_thresh = thresholds.get(selected_model_name, 0.5)
user_threshold = st.sidebar.slider("Classification Threshold", 0.1, 0.9, float(default_thresh))

# --- MAIN DASHBOARD ---
st.title("Chicago Crime Arrest Prediction Dashboard")
st.markdown(f"**Current Model:** {selected_model_name} | **Optimized Threshold:** {default_thresh:.2f}")

col1, col2 = st.columns(2)

with col1:
    st.subheader("Predict Arrest Probability")
    # Feature Input form
    with st.form("prediction_form"):
        crime_type = st.selectbox("Primary Crime Type", ["THEFT", "BATTERY", "ASSAULT", "NARCOTICS", "OTHER"])
        district = st.number_input("Police District", min_value=1, max_value=31, value=11)
        hour = st.slider("Hour of Day", 0, 23, 12)
        month = st.slider("Month", 1, 12, 4)
        is_domestic = st.checkbox("Domestic Violence Case?")
        
        submit = st.form_submit_button("Run Analysis")

    if submit:
        # Construct feature vector (Minimal example - must match your 60 features)
        # In a full app, you would reconstruct the dummy variables here.
        st.info("Calculating probability based on spatial and temporal features...")
        # (Simplified for demonstration)
        mock_features = np.zeros((1, 60)) 
        # Apply scaler
        scaled_features = scaler.transform(mock_features)
        
        prob = current_model.predict_proba(scaled_features)[0, 1]
        result = "ARREST LIKELY" if prob >= user_threshold else "ARREST UNLIKELY"
        
        st.metric("Arrest Probability", f"{prob*100:.2f}%")
        st.success(f"Prediction: {result}")

with col2:
    st.subheader("Model Evaluation Insights")
    # Display the static images generated by your pipeline
    tab1, tab2 = st.tabs(["ROC Curve", "Feature Importance"])
    
    with tab1:
        st.image("roc_curves.png", caption="Model Comparison (AUC-ROC)")
    
    with tab2:
        st.image("feature_importance.png", caption="Top Predictors (Random Forest)")

# --- FOOTER ---
st.divider()
st.markdown("Created by Team 5 | Data Source: Chicago CLEAR System (2015-2024)")
